title: "[改善したい課題のタイトルを記入] "
body:
  - type: markdown
    attributes:
      value: "# 概要"
  - type: textarea
    id: overview
    attributes:
      label: _
      value: |
        <ここに概要を記入>
    validations:
      required: true
  - type: markdown
    attributes:
      value: "# 現状の問題点"
  - type: textarea
    id: issue
    attributes:
      label: _
      value: |
        <ここに現状の問題点を記入>
    validations:
      required: true
  - type: markdown
    attributes:
      value: "# 解決のためのたたき台"
  - type: textarea
    id: solution
    attributes:
      label: _
      value: |
        <何かたたき台があれば、ここに記入>
    validations:
      required: false